v: 0
 
meta_repo: "https://github.com/ezsystems/ezplatform.git"
require: "ezsystems/demobundle:dev-master as 6.0.x-dev"


ci:
  system:
    matrix:
     - 
      install: "demo"
      arguments: "--profile demo --suite content"
     - 
      install: "demo-clean"
      arguments: "--profile demo --suite clean"
     - 
#      install: "demo-clean" # not mandatory
      arguments: "--profile rest --suite fullJson"
