v: 0
 
#meta_repo: "https://github.com/ezsystems/ezplatform.git"

#only needed if you need to create alias
require: "ezsystems/demobundle:dev-master as 6.0.x-dev"


integrate:
  matrix:
   -
    install: "demo"
    arguments: "--profile demo --suite content"
    require:
    meta_repo: "https://github.com/ezsystems/ezplatform.git"
   -
    install: "demo-clean"
    arguments: "--profile demo --suite clean"
    meta_repo: "https://github.com/ezsystems/ezstudio.git"
   -
#     install: "demo-clean" # not mandatory
    arguments: "--profile rest --suite fullJson"
   -
#     install: "demo-clean" # not mandatory
    arguments: "--profile rest --suite fullXml"
